from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable, List, Optional


class FileManager:
    """Manage the office_ai_files workspace and file saving with graceful fallbacks.

    Directory layout (created on init if missing):
      office_ai_files/
        documents/
        presentations/
        spreadsheets/
        templates/
        exports/

    Save methods:
    - save_text_document(title, content)
    - save_text_presentation(title, slides)
    - save_text_spreadsheet(title, rows)
    - save_docx_document(title, paragraphs) -> falls back to text if python-docx missing
    - save_pptx_presentation(title, slides) -> falls back to text if python-pptx missing
    - save_xlsx_workbook(title, rows)       -> falls back to text if openpyxl missing
    """

    DOCUMENTS = "documents"
    PRESENTATIONS = "presentations"
    SPREADSHEETS = "spreadsheets"
    TEMPLATES = "templates"
    EXPORTS = "exports"

    def __init__(self, base_dir: Optional[str] = None) -> None:
        if base_dir is None:
            base_dir = str(Path.cwd() / "office_ai_files")
        self.base_dir = Path(base_dir)
        self._ensure_base_dirs()

    # ---------- Directory helpers ----------
    def _ensure_base_dirs(self) -> None:
        (self.base_dir / self.DOCUMENTS).mkdir(parents=True, exist_ok=True)
        (self.base_dir / self.PRESENTATIONS).mkdir(parents=True, exist_ok=True)
        (self.base_dir / self.SPREADSHEETS).mkdir(parents=True, exist_ok=True)
        (self.base_dir / self.TEMPLATES).mkdir(parents=True, exist_ok=True)
        (self.base_dir / self.EXPORTS).mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _slugify(name: str) -> str:
        safe = [c if c.isalnum() or c in ("-", "_", ".", " ") else "_" for c in name.strip()]
        s = "".join(safe).strip().replace(" ", "_")
        return s or "untitled"

    @staticmethod
    def _unique_path(path: Path) -> Path:
        if not path.exists():
            return path
        stem = path.stem
        suffix = path.suffix
        parent = path.parent
        i = 1
        while True:
            candidate = parent / f"{stem}_{i}{suffix}"
            if not candidate.exists():
                return candidate
            i += 1

    # ---------- Text fallbacks ----------
    def save_text_document(self, title: str, content: str) -> dict:
        filename = f"{self._slugify(title)}.txt"
        path = self._unique_path(self.base_dir / self.DOCUMENTS / filename)
        path.write_text(content, encoding="utf-8")
        return {"status": "ok", "file_path": str(path)}

    def save_text_presentation(self, title: str, slides: Iterable[str]) -> dict:
        filename = f"{self._slugify(title)}.txt"
        path = self._unique_path(self.base_dir / self.PRESENTATIONS / filename)
        lines = []
        for idx, slide in enumerate(slides, start=1):
            lines.append(f"# Slide {idx}")
            lines.append(str(slide))
            lines.append("")
        path.write_text("\n".join(lines), encoding="utf-8")
        return {"status": "ok", "file_path": str(path)}

    def save_text_spreadsheet(self, title: str, rows: Iterable[Iterable[object]]) -> dict:
        filename = f"{self._slugify(title)}.txt"
        path = self._unique_path(self.base_dir / self.SPREADSHEETS / filename)
        lines = []
        for row in rows:
            line = "\t".join("" if v is None else str(v) for v in row)
            lines.append(line)
        path.write_text("\n".join(lines), encoding="utf-8")
        return {"status": "ok", "file_path": str(path)}

    # ---------- Rich formats with graceful fallback ----------
    def save_docx_document(self, title: str, paragraphs: Iterable[str]) -> dict:
        try:
            import docx  # python-docx
        except Exception:
            return self.save_text_document(title, "\n\n".join(paragraphs))

        filename = f"{self._slugify(title)}.docx"
        path = self._unique_path(self.base_dir / self.DOCUMENTS / filename)
        doc = docx.Document()
        # Optional: first paragraph as heading if present
        first = None
        it = iter(paragraphs)
        try:
            first = next(it)
        except StopIteration:
            first = None
        if first:
            doc.add_heading(first, level=1)
        for p in it:
            doc.add_paragraph(p)
        if not first:
            doc.add_paragraph("")
            doc.add_paragraph("Generated by OfficeAIAgent")
        doc.save(str(path))
        return {"status": "ok", "file_path": str(path)}

    def save_pptx_presentation(self, title: str, slides: Iterable[str]) -> dict:
        try:
            from pptx import Presentation  # python-pptx
            from pptx.util import Inches
        except Exception:
            return self.save_text_presentation(title, slides)

        filename = f"{self._slugify(title)}.pptx"
        path = self._unique_path(self.base_dir / self.PRESENTATIONS / filename)
        prs = Presentation()
        layout = prs.slide_layouts[1]  # Title and Content
        for idx, content in enumerate(slides, start=1):
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = f"{title} - Slide {idx}"
            slide.placeholders[1].text = str(content)
        prs.save(str(path))
        return {"status": "ok", "file_path": str(path)}

    def save_xlsx_workbook(self, title: str, rows: Iterable[Iterable[object]]) -> dict:
        try:
            from openpyxl import Workbook
        except Exception:
            return self.save_text_spreadsheet(title, rows)

        filename = f"{self._slugify(title)}.xlsx"
        path = self._unique_path(self.base_dir / self.SPREADSHEETS / filename)
        wb = Workbook()
        ws = wb.active
        for row in rows:
            ws.append(list(row))
        wb.save(str(path))
        return {"status": "ok", "file_path": str(path)}

