from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional

from .base_agent import BaseOfficeAgent


class DocumentAgent(BaseOfficeAgent):
    """Word-focused agent that composes a simple document using tools."""

    def _initialize_tools(self):
        return [
            "create_document",
            "add_heading",
            "add_paragraph",
            "save_document",
        ]

    def _get_system_prompt(self) -> str:
        return "Create concise, well-structured documents with a clear heading and body."

    def execute(self, task, context=None, user_id=None, task_id=None):
        title = (context or {}).get("title") or self._extract_title(str(task)) or "Generated Document"
        create = self._tool("create_document")
        add_h = self._tool("add_heading")
        add_p = self._tool("add_paragraph")
        save = self._tool("save_document")

        # Try Gemini for structured document content
        spec = self._generate_document_with_gemini(task=str(task), title=title)

        doc_id = create(title=title)["doc_id"]
        if spec:
            add_h(doc_id=doc_id, text=spec.get("title") or title)
            sections = spec.get("sections") or []
            if isinstance(sections, list):
                for sec in sections:
                    heading = sec.get("heading") if isinstance(sec, dict) else None
                    if heading:
                        add_h(doc_id=doc_id, text=str(heading))
                    paras = sec.get("paragraphs") if isinstance(sec, dict) else None
                    if isinstance(paras, list):
                        for p in paras:
                            add_p(doc_id=doc_id, text=str(p))
        else:
            # Deterministic fallback
            add_h(doc_id=doc_id, text=title)
            add_p(doc_id=doc_id, text=str(task))
            add_p(doc_id=doc_id, text="Generated by DocumentAgent")
        return save(doc_id=doc_id)

    # --------------------- Gemini draft generation ---------------------
    def _generate_document_with_gemini(self, task: str, title: str) -> Optional[Dict[str, Any]]:
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            return None
        try:
            import google.generativeai as genai  # type: ignore

            genai.configure(api_key=api_key)
            primary = os.getenv("LLM_MODEL", "gemini-1.5-pro")
            candidates = [primary, "gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro"]
            seen, fallbacks = set(), []
            for m in candidates:
                if m not in seen:
                    seen.add(m)
                    fallbacks.append(m)

            prompt = (
                "You are a writing assistant. Draft a short, clear document titled '"
                + title
                + "'. Return ONLY valid JSON with this schema and no extra text:\n"
                "{\n  \"title\": \"Document Title\",\n  \"sections\": [\n    { \"heading\": \"Section Heading\", \"paragraphs\": [\"para1\", \"para2\"] },\n    ...\n  ]\n}\n"
                f"Task: {task}"
            )
            last_err = None
            for model_name in fallbacks:
                try:
                    model = genai.GenerativeModel(model_name)
                    resp = model.generate_content(prompt)
                    last_err = None
                    break
                except Exception as _e:
                    last_err = _e
                    continue
            if last_err:
                raise last_err
            text = getattr(resp, "text", None) or getattr(resp, "candidates", None)
            if isinstance(text, list):
                text = "\n".join(str(x) for x in text)
            if not isinstance(text, str):
                text = str(resp)
            data = self._extract_json(text)
            if not isinstance(data, dict):
                return None
            # normalize
            title_out = data.get("title") or title
            sections = data.get("sections") if isinstance(data.get("sections"), list) else []
            return {"title": title_out, "sections": sections}
        except Exception as e:  # pragma: no cover
            self.logger.warning("Gemini document generation failed: %s", e)
            return None

    @staticmethod
    def _extract_json(text: str) -> Optional[dict]:
        try:
            return json.loads(text)
        except Exception:
            pass
        m = re.search(r"\{[\s\S]*\}", text)
        if m:
            try:
                return json.loads(m.group(0))
            except Exception:
                return None
        return None

    @staticmethod
    def _extract_title(task: str) -> Optional[str]:
        m = re.search(r"(?:about|on)\s+(.+)$", str(task), re.IGNORECASE)
        return m.group(1).strip().rstrip(".") if m else None
